### ISSUE TITLE
`Grafana Agent Node Exporter Quickstart` dashboard fails out of the box

### ISSUE THREAD

**Issue by nobuto-m** [canonical/grafana-agent-operator#24]
### Bug Description

The `Grafana Agent Node Exporter Quickstart` dashboard added by the charm simply fails.

![Screenshot from 2023-10-26 21-36-43](https://github.com/canonical/grafana-agent-operator/assets/4356209/a5a11aad-a821-4ec0-ba46-9e0f1338bc08)

### To Reproduce

With MAAS provider, deploy the grafana-agent charm, relate it to a principle charm and to the COS.

### Environment

```
SAAS                   Status  Store            URL
cos-alertmanager       active  maas-controller  admin/cos.alertmanager-karma-dashboard
cos-grafana            active  maas-controller  admin/cos.grafana-dashboards
cos-loki               active  maas-controller  admin/cos.loki-logging
cos-prometheus         active  maas-controller  admin/cos.prometheus-receive-remote-write
cos-prometheus-scrape  active  maas-controller  admin/cos.prometheus-scrape

App                Version  Status  Scale  Charm                   Channel        Rev  Exposed  Message
ceph-osd           17.2.6   active      3  ceph-osd                                15  no       Unit is ready (2 OSD)
grafana-agent               active     13  grafana-agent           latest/edge     20  no       
ntp                4.2      active      3  ntp                     stable          50  no       chrony: Ready
```

### Relevant log output

```shell
N/A
```

**Comment by guimaluf** [comment]
Digging a little bit into that I found that the dashboard relies on the variable `instance` to generate its queries. Since the variable query is returning empty all metrics are filtered with  `{instance=""}`, thus not showing any data.

Despite the wrong data source for the `instance`, e.g "Query Options - Data source - $datasource - not found"  
The variable query doesn't seem to show any result.
`label_values(node_exporter_build_info{job="integrations/node_exporter"}, instance)`
